
ID_GROUP = 0
ID_AUTO_MATCH = 1
ID_GENERATE = 2
ID_GENERATE_AND_PLACE_ORDER = 3
ID_ROTATIONS = 4
ID_MAPPINGS = 5
ID_SETTINGS = 6

ID_MANUAL_MATCH = 7
ID_REMOVE_PART = 8
ID_SELECT_SAME_PARTS = 9
ID_PART_DETAILS = 10
ID_TOGGLE_BOM = 11
ID_TOGGLE_POS = 12
ID_SAVE_MAPPINGS = 13
ID_EXPORT = 14